config/routes.rb
PMate::Application.routes.draw do

  resources :users
  resources :sessions, :only =>[:new, :destory, :create]

  
  match '/register',  :to=> 'users#new'

  get "users/edit"

  match '/about',   :to=> 'pages#about'
  match '/contact', :to=> 'pages#contact'
  match '/help',    :to=> 'pages#help'
  match '/signin',  :to=> 'sessions#new'
  match '/signout', :to=> 'sessions#destroy'

  
  root :to=> 'pages#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  first_name         :string(75)
#  last_name          :string(75)
#  email              :string(255)
#  address            :string(255)
#  city               :string(100)
#  state              :string(25)
#  zip                :string(25)
#  office_phone       :string(25)
#  cell_phone         :string(25)
#  fax                :string(25)
#  user_type          :integer
#  approver_level_id  :integer
#  employee           :boolean
#  supervisor_id      :integer
#  ccb_member         :integer
#  encrypted_password :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  salt               :string(255)
#

require 'digest'

class User < ActiveRecord::Base
  attr_accessor   :password
  attr_accessor   :full_name
  
  attr_accessible :first_name,
                  :last_name,
                  :email,
                  :address,
                  :city,
                  :state,
                  :zip,
                  :office_phone,
                  :cell_phone,
                  :fax,
                  :user_type,
                  :approver_level_id,
                  :employee,
                  :supervisor_id,
                  :ccb_member,
                  :password,
                  :password_confirmation
                  
                
  attr_readonly   :created_at, :updated_at, :full_name

  #for email validating
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :last_name, :presence=> true,
                        :length=> {:maximum=>50}

  validates :email,     :presence=> true,
                        :length=>{:maximum=>255},
                        :format=>{:with=>email_regex},
                        :uniqueness=>{:case_sensitive=> false}

  # Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }

  before_save :encrypt_password

  # Return true if the user's password matches the submitted password.
  def has_password?(submitted_password)
    # Compare encrypted_password with the encrypted version of
    # submitted_password.
    encrypted_password == encrypt(submitted_password)
  end

  #here's how we log in
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  #a nice way to return the full users name
  def full_name
    return "#{self.first_name} #{self.last_name}"
  end
  

    private

    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end






end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  include ApplicationHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
	@title = "Home"
  end

  def contact
    @title = "Contact Us"
  end

  def about
    @title = "About Us"
  end

  def help
    @title = "Help"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign In"
  end

  def create
    
    if request.post?
      user = User.authenticate(params[:session][:email],
                              params[:session][:password])
      if user.nil?
        # oooops nobody there

        flash.now[:error] = "Invalid email and password combination"
        
        @title = "Sign In"
        render 'new'
        
      else
        #someone there

        sign_in user

        redirect_to user
        flash[:success] = "Hi there #{current_user.full_name}!"
        
      end
    end
  end

  def destroy
    
    sign_out
    redirect_to root_path

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate, :only => [:edit, :update, :show]

  def new
    @title = "Create a User"
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      
      flash[:success] = "Welcome to pMate!"
      
      sign_in @user #you can find this in the sessions_helper
      
      
      redirect_to @user

    else
      @title = "Create a User"
      render 'new'
    end
  end


  def edit
    @title = "Edit User"
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
    
      flash[:success] = "Profile Updated"
      redirect_to @user
    else
      @title="Edit User"
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @title = @user.first_name + " " + @user.last_name
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis.
  def title
    base_title = "pMate"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
  def authenticate
    deny_access unless signed_in?
  end
  
  def deny_access
    redirect_to signin_path, :notice=> "You need to be signed in to access that content!"
  end


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user.id
    self.current_user=user
    
  end

  def current_user=(user)
    @current_user= user
  end

  def current_user
    if signed_in?
      @current_user ||= User.find(session[:user_id])
    end
    
  end

  def signed_in?
    !session[:user_id].nil?
  end

  def sign_out
    session[:user_id] = nil
    self.current_user = nil
  end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  
    <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/book">Rails Tutorial</a></li>
    </ul>
  </nav>

 
</footer>

app/views/layouts/_header.html.erb
<header>
  <div id="menu">

    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
       <% if signed_in? %>
         <li><%= link_to "Profile", current_user %></li>
         <li><%= link_to "Settings", edit_user_path(current_user) %></li>
         <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Register", register_path %></li>
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>

    </ul>
  </div>
       
</header>
 <div id="logo"><h1><%= title %> </h1></div>

app/views/layouts/_stylesheets.html.erb
  <%= csrf_meta_tag %>

  <%= javascript_include_tag :defaults %>

  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->

  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
 <!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
 <%= stylesheet_link_tag 'custom', :media=> 'screen' %>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>

    <%=  render 'layouts/stylesheets' %>

  </head>
  <body>
   
    <div id="wrapper">
      <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
      <% end %>

      <%= render 'layouts/header' %>
      <hr />
	<div id="page">
         
            <%= yield %>
        
	</div>

      <div style="clear: both;">&nbsp;</div>
      
       <%= render 'layouts/footer' %>
       <%= debug(params) if Rails.env.development? %>
    </div>
   
  </body>
</html>

app/views/pages/about.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "about.html" %>

app/views/pages/contact.html.erb
<div id="content">
  <h1>Pages#contact</h1>
    <p>Find me in app/views/pages/contact.html.erb</p>
</div>

app/views/pages/help.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "help.html" %>

app/views/pages/home.html.erb
<div id="content">
	<h1>Pages#home</h1>
	<h2> Ya gatta be kiddin me! </h2>
	<p>Find me in app/views/pages/home.html.erb</p>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Let's get started...</h1>

<p>Just a few steps and we'll get you up and going!</p>

<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages', :object => f.object %>


  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions round">
    <%= f.submit "Register" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>
  
</h1>
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= @user.first_name %> <%= @user.last_name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.full_name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>